{% set name = "click" %}
{% set version = "8.2.2" %}
{% set python_min = "3.10" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/click-{{ version }}.tar.gz
  sha256: 068616e6ef9705a07b6db727cb9c248f4eb9dae437a30239f56fa94b18b852ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core <4
    - pip
  run:
    - python >={{ python_min }}
    - colorama   # [win]
    - __win      # [win]
    - __unix     # [unix]

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - click
  commands:
    - pip check

about:
  home: https://palletsprojects.com/p/click/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Composable command line interface toolkit
  description: |
    Click is a Python package for creating beautiful command line interfaces
    in a composable way with as little code as necessary. It's the "Command
    Line Interface Creation Kit". It's highly configurable but comes with
    sensible defaults out of the box.

    It aims to make the process of writing command line tools quick and fun
    while also preventing any frustration caused by the inability to
    implement an intended CLI API.

    Click in three points:

    -   Arbitrary nesting of commands
    -   Automatic help page generation
    -   Supports lazy loading of subcommands at runtime
  dev_url: https://github.com/pallets/click/
  doc_url: https://click.palletsprojects.com/

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
