{% set version = "5.1" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/click/click-{{ version }}.tar.gz
  sha256: 678c98275431fad324275dec63791e4a17558b40e5a110e20a82866139a85a5a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - click

about:
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Python composable command line interface toolkit'
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
