travis:
  secure:
    BINSTAR_TOKEN: TmAqB8cckhEvxBk7SA3HXRymQ8Nu+lvmjKGNP46+tYqfAIXhcEqixpaN/4gNyxCjLbClRUjuQvuR4Wem55tSzPHHL8Wmz7WVWMwsDUSNIWx5ORmkVMJMyLJiuvZFvOGypKo2+e1omHfk0jRX58JHXEu/IMLyA3jcL7c4rnvs+wAddcI5Rpu89+Dnp3TTFjfAUxKPV996TFAhwXAHEd/XeXCpn+7avM9HCwS1oC0ZYe1NARzG+vsdw7Z+Z/FLJkryrBAXfos1roXqxR2qGORd9tHFHJq9nIcj+4cCxdw5iL7UmFqM91WaPYdTl0Z/Kke7IMm6/xpJQHCoETlQJ+YdjhpvQKZZBR+n0AJwp0zp8oosfjr5WcJTIJcMOoN1IuAfWp15PgNCWpsB8HPN2GgzUpMhkGKAixQfpfo+MOBPU3nbQ7Fls+wwv0o5M3KQrCpklng3LvnsKN01+zmoFGAp+s2tkbxrYYKo8qXeZl+i+d0zlq9N2hNrYIFpNYiEUM8G6D0Y9FgB2YcE8sKwiEapsEdY7BAi8TNzRB1ArisFRPO+nODPWJ6ZHnThg8suGlHo64Va+IhG7hoDbfiCDE6/ODGpc7tN4bNxdFjCgeSMsOYuhtiFJTa3T7UwaxM0l6eQK0ZtH3pKYx3xGyA2FeB0dW4/nN8omrpMsmf0virnZpg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
